version: "3.9"
networks:
  roboshop:
    driver: bridge
   # This is equvalent to the docker volume create [volume-name] these are  named volumes                
services:
  web:
    image: richeb/web:v1
    container_name: web
    ports:
      - "80:80"
  mongodb:
    image: richeb/mongodb:v1
    container_name: mongodb
  catalogue:
    image: richeb/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  redis:
    image: redis
  user:
    image: user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart:
    image: richeb/cart:v1
    container_name: cart
    depends_on:
      - catalogue
      - redis
  mysql:
    image: richeb/mysql:v1
    container_name: mysql
       
  shipping:
    image: richeb/shipping:v1
    container_name: shipping
    depends_on:
      - mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
  payment:
    image: richeb/payment:v1
    container_name: payment
    depends_on:
      - rabbitmq
  rating:
    image: richeb/ratings:v1
    container_name: rating
    depends_on:
      - catalogue
   

# The dependencies for every module developer will tell us no need to woryy abt it      
