version: "3.9"
networks:
  roboshop:
    driver: bridge
services:
  web:
    image: web:v1
    container_name: web
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis
  user:
    image: user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  
