version: "3.9"
networks:
  roboshop:
    driver: bridge
   # This is equvalent to the docker volume create [volume-name] these are  named volumes 
volumes:
 mysql:
  driver: local
  driver_opts:
   o: bind
   type: none
   device: /home/ec2-user/mysql    
 rabbitmq:
  driver: local
  driver_opts:
   o: bind
   type: none
   device: /home/ec2-user/rabbitmq
 mongodb:
  driver: local
  driver_opts:
   o: bind
   type: none
   device: /home/ec2-user/mongodb
 redis:
  driver: local
  driver_opts:
   o: bind
   type: none
   device: /home/ec2-user/redis               
services:
  web:
    image: web:v1
    container_name: web
    ports:
      - "80:80"
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  redis:
    image: redis
    volumes:
    - redis:/data
  user:
    image: user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart:
    image: cart:v1
    container_name: cart
    depends_on:
      - catalogue
      - redis
  mysql:
    image: mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql    
  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
      - mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  payment:
    image: payment:v1
    container_name: payment
    depends_on:
      - rabbitmq
  rating:
    image: ratings:v1
    container_name: rating
    depends_on:
      - catalogue
   

# The dependencies for every module developer will tell us no need to woryy abt it      
